### ISSUE TITLE
Verify not working

### ISSUE THREAD

**Issue by cullnm** [Momentum-Free/sledgehammer-bot-docs#11]
![image](https://user-images.githubusercontent.com/31957904/233537912-abb0af45-a511-4472-af37-c41e1ae38025.png)

Verification is not working and new users can see the all channels
Do I need to do some configuration?

**Comment by Chinoman10** [comment]
Hello @raika-dev ,

We aren't actively monitoring issues on this repository, so sorry for getting back to you so many months later.

Yes, there is a certain level of configuration you need to do for your server before Sledgehammer is working 100% as it should.

Please join our server so we can help: discord.gg/aHQkQUtEGR
