### ISSUE TITLE
Suggestion: Translation for words too 

### ISSUE THREAD

**Issue by WyvernNE** [Momentum-Free/sledgehammer-bot-docs#5]
Hello!

Would it be possible to translate the word that we need to search the emoji for? :)

**Comment by Chinoman10** [comment]
This is a very good point which we've missed...
Will add it to the roadmap @WyvernNE , thanks!

PS: Sorry for taking so long to get back to you, we aren't actively monitoring these issues in here --> everything's going through our Discord server: https://discord.gg/aHQkQUtEGR
