### ISSUE TITLE
Cant see icon for to verify discords

### ISSUE THREAD

**Issue by yolo1111** [Momentum-Free/sledgehammer-bot-docs#6]
Check attached image. How i can fix It?

Kind regards
Xxx
![Screenshot_2022-09-02-21-48-44-644_com discord](https://user-images.githubusercontent.com/66553119/188227510-ae6afdcb-f1d7-4a70-81b0-4a75a6c87cbd.jpg)

**Comment by Chinoman10** [comment]
https://techartful.com/discord-embed-not-working/#:~:text=1.%20Activate%20Link/Website%20Preview%20Option

You have embedded messages turned off.
